CREATE TABLE task (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
    title VARCHAR(200) NOT NULL, 
    is_completed BOOLEAN NOT NULL DEFAULT 0, 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
